owner: joysulaiman00
repo: cairn-status

sites:
  - name: Cairn University
    url: https://cairn.edu
  - name: Cairn eLearning
    url: https://elearning.cairn.edu
  - name: Cairn Self Service
    url: https://selfservice.cairn.edu/SelfService/Home/LogIn?ReturnUrl=%2FSelfService%2F

status-website:
  name: Cairn University System Status
